### ISSUE TITLE
RDP auth

### ISSUE THREAD

**Issue by astro-train** [galkan/crowbar#12]
I'am not yet tried the tool, but played a little bit with Windows XP with RDP on, and status is always returned as 0 no matter if I provided working user:password pair. I used latest source code  atm to build binaries on windows 7. Is there a solution that help to certain determine status of authentication?

**Comment by g0tmi1k** [comment]
I can confirm this.
Fix was to follow this: http://opentechnotes.blogspot.co.uk/2015/02/compile-headless-freerdp-credential-checking.html

**Comment by astro-train** [comment]
@g0tmi1k, Did you test how it handles winxp/win2003 now?

**Comment by g0tmi1k** [comment]
The issue is with the package, not the target.

**Comment by astro-train** [comment]
@g0tmi1k, oh I see now. Thanks for info!
