### ISSUE TITLE
PIP package `nmap` has nothing to do with the port scanner

### ISSUE THREAD

**Issue by Pamplemousse** [galkan/crowbar#43]
The referenced `nmap` python package in `requirements.txt` has nothing to do with the port scanner; See: https://pypi.org/project/nmap/ .

The test to see if either the binary is present in [https://github.com/galkan/crowbar/blob/c2d8da1db2d5ce57c8984f92e4a177075cd5d47c/lib/nmap.py#L19-L28](lib/nmap.py#L19-L28) could be simplified (as imported the `nmap` from pip is certainly of no help).

**Comment by g0tmi1k** [comment]
Feel free to put in a PR to correct it :)

**Comment by g0tmi1k** [comment]
Cheers for putting in the time to follow up and do a PR <3
