### ISSUE TITLE
File doesn't exist

### ISSUE THREAD

**Issue by bu3alwa** [galkan/crowbar#47]
```
 $ ./crowbar.py -b rdp -u admin -s 10.11.0.22/32 -n 4 -C /usr/share/wordlists/rockyou.txt
2020-05-15 00:46:28 START
2020-05-15 00:46:28 Crowbar v0.4.2-dev
2020-05-15 00:46:28 Trying 10.11.0.22:3389
File: /usr/share/wordlists/rockyou.txt doesn't exists

$ head /usr/share/wordlists/rockyou.txt 
123456
12345
123456789
password
iloveyou
princess
1234567
rockyou
12345678
abc123

 $ ls -la /usr/share/wordlists/rockyou.txt 
-rw-rw-rw- 1 kali kali 139921507 Jul 17  2019 /usr/share/wordlists/rockyou.txt
```

Is this a bug or am I doing something wrong?

**Comment by bickerle** [comment]
I ran into the same problem. The issue lies in the encoding of rockyou.txt.
crowbar assumes utf8 encoding but there are non-utf8 characters in there. Unfortunately crowbar prints "File: ... doesn't exist" for any exception that occurs while reading the file.

**Comment by bu3alwa** [comment]
> 
> 
> I ran into the same problem. The issue lies in the encoding of rockyou.txt.
> crowbar assumes utf8 encoding but there are non-utf8 characters in there. Unfortunately crowbar prints "File: ... doesn't exist" for any exception that occurs while reading the file.
> Edit: you can filter out those lines with `grep -ax '.*' rockyou.txt > rockyou-utf8.txt` or you might be able to convert it using `iconv`.

Awesome, thanks for the reply. I've had multiple issues with running my rockyou file and I think this is it.
