### ISSUE TITLE
Request a new optional

### ISSUE THREAD

**Issue by Stepman123** [galkan/crowbar#7]
A new method rdplogin. When users and hosts are already known, only need to brute force the password.

**Comment by g0tmi1k** [comment]
From my understanding, you can do that already with `-b rdp`.

Single host, single username, single password: 
```
python crowbar.py -b rdp -s 10.1.1.27/32 -u administrator -c check_this_password
```

Single host, single username, password list
```
python crowbar.py -b rdp -s 10.1.1.27/32 -u administrator -C /usr/share/wordlists/rockyou.txt
```
