### ISSUE TITLE
CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by sec13b** [galkan/crowbar#82]
/home/kali/.local/lib/python3.11/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
2023-05-18 02:24:51 START

how to set ?
i try all . 
to run in in python2.7 ?

**Comment by codeburrito** [comment]
hey @sec13b, I recently found a workaround for this, try out the following upgrade 
`pip install paramiko --upgrade` 
This got rid the same error you received.

**Comment by sec13b** [comment]
ok ,thank you
